"""Quiz-related Temporal activities with real database operations."""

from datetime import datetime
from typing import List, Optional
from uuid import UUID, uuid4

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from temporalio import activity

from app.config import settings
from app.logs.logger import get_logger
from app.models.quiz import Quiz, QuizQuestion, QuizAttempt, QuestionResponse
from app.models.book import BookChapter
from app.models.learning import LearningState

logger = get_logger(__name__)

# Database setup
_engine = None
_session_factory = None


def get_engine():
    """Get or create database engine."""
    global _engine
    if _engine is None:
        _engine = create_async_engine(
            settings.database_url,
            pool_size=5,
            max_overflow=10,
        )
    return _engine


def get_session_factory():
    """Get or create session factory."""
    global _session_factory
    if _session_factory is None:
        _session_factory = sessionmaker(
            bind=get_engine(),
            class_=AsyncSession,
            expire_on_commit=False,
        )
    return _session_factory


async def get_db_session() -> AsyncSession:
    """Get a database session for activities."""
    factory = get_session_factory()
    return factory()


@activity.defn
async def generate_chapter_quiz(
    book_id: str,
    chapter_id: str,
    user_id: str,
) -> dict:
    """
    Generate a chapter-end quiz.
    
    Args:
        book_id: The book's ID
        chapter_id: The chapter's ID
        user_id: The user's ID
        
    Returns:
        Dict with quiz information
    """
    activity.logger.info(
        f"Generating quiz for user {user_id}, chapter {chapter_id}"
    )
    
    async with await get_db_session() as db:
        try:
            # Get chapter info
            chapter_result = await db.execute(
                select(BookChapter)
                .where(BookChapter.id == UUID(chapter_id))
            )
            chapter = chapter_result.scalar_one_or_none()
            
            if not chapter:
                return {"success": False, "error": "Chapter not found"}
            
            # Check if quiz already exists for this chapter
            existing_quiz = await db.execute(
                select(Quiz)
                .where(Quiz.book_id == UUID(book_id))
                .where(Quiz.chapter_id == UUID(chapter_id))
                .where(Quiz.quiz_type == "chapter_end")
            )
            quiz = existing_quiz.scalar_one_or_none()
            
            if quiz:
                # Return existing quiz
                logger.info(
                    "using_existing_quiz",
                    quiz_id=str(quiz.id),
                    chapter_id=chapter_id,
                )
                return {
                    "success": True,
                    "quiz_id": str(quiz.id),
                    "existing": True,
                    "total_questions": quiz.total_questions,
                }
            
            # Create new quiz
            quiz = Quiz(
                id=uuid4(),
                book_id=UUID(book_id),
                chapter_id=UUID(chapter_id),
                quiz_type="chapter_end",
                title=f"Chapter {chapter.chapter_number} Quiz",
                total_questions=settings.questions_per_quiz,
                passing_score=settings.quiz_passing_score,
                time_limit_minutes=30,
            )
            db.add(quiz)
            
            # Generate placeholder questions
            # In production, these would be generated by the QuizAgent with LLM
            key_concepts = chapter.key_concepts or []
            
            for i in range(settings.questions_per_quiz):
                topic = key_concepts[i % len(key_concepts)] if key_concepts else f"Topic {i+1}"
                
                question = QuizQuestion(
                    id=uuid4(),
                    quiz_id=quiz.id,
                    book_id=UUID(book_id),
                    chapter_id=UUID(chapter_id),
                    question_text=f"Question {i+1} about {topic}",
                    question_type="mcq" if i % 3 == 0 else "true_false" if i % 3 == 1 else "short_answer",
                    options=["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"] if i % 3 == 0 else None,
                    correct_answer="A" if i % 3 == 0 else "true" if i % 3 == 1 else "Understanding of concept",
                    explanation=f"This tests your understanding of {topic}.",
                    difficulty="medium",
                    topic=topic,
                )
                db.add(question)
            
            # Update learning state to quiz mode
            await db.execute(
                update(LearningState)
                .where(LearningState.user_id == UUID(user_id))
                .where(LearningState.book_id == UUID(book_id))
                .values(
                    quiz_mode="chapter_quiz",
                    pending_quiz_questions={"quiz_id": str(quiz.id), "remaining": settings.questions_per_quiz},
                    updated_at=datetime.utcnow(),
                )
            )
            
            await db.commit()
            
            logger.info(
                "quiz_generated",
                quiz_id=str(quiz.id),
                chapter_id=chapter_id,
                questions=settings.questions_per_quiz,
            )
            
            return {
                "success": True,
                "quiz_id": str(quiz.id),
                "existing": False,
                "total_questions": settings.questions_per_quiz,
                "chapter_number": chapter.chapter_number,
                "chapter_title": chapter.title,
            }
            
        except Exception as e:
            await db.rollback()
            logger.exception("generate_quiz_failed", error=str(e))
            return {"success": False, "error": str(e)}


@activity.defn
async def process_quiz_results(
    user_id: str,
    quiz_id: str,
) -> dict:
    """
    Process completed quiz results.
    
    Args:
        user_id: The user's ID
        quiz_id: The quiz ID
        
    Returns:
        Dict with quiz results
    """
    activity.logger.info(f"Processing quiz results for user {user_id}, quiz {quiz_id}")
    
    async with await get_db_session() as db:
        try:
            # Get the quiz attempt
            attempt_result = await db.execute(
                select(QuizAttempt)
                .where(QuizAttempt.user_id == UUID(user_id))
                .where(QuizAttempt.quiz_id == UUID(quiz_id))
                .where(QuizAttempt.completed_at.isnot(None))
                .order_by(QuizAttempt.completed_at.desc())
            )
            attempt = attempt_result.scalar_one_or_none()
            
            if not attempt:
                return {"success": False, "error": "Quiz attempt not found"}
            
            # Get quiz info
            quiz_result = await db.execute(
                select(Quiz).where(Quiz.id == UUID(quiz_id))
            )
            quiz = quiz_result.scalar_one_or_none()
            
            if not quiz:
                return {"success": False, "error": "Quiz not found"}
            
            # Calculate detailed results
            responses_result = await db.execute(
                select(QuestionResponse)
                .where(QuestionResponse.attempt_id == attempt.id)
            )
            responses = responses_result.scalars().all()
            
            correct_count = sum(1 for r in responses if r.is_correct)
            total_count = len(responses)
            score = correct_count / total_count if total_count > 0 else 0.0
            
            # Determine weak areas
            questions_result = await db.execute(
                select(QuizQuestion)
                .where(QuizQuestion.quiz_id == UUID(quiz_id))
            )
            questions = {str(q.id): q for q in questions_result.scalars().all()}
            
            weak_areas = []
            for response in responses:
                if not response.is_correct:
                    question = questions.get(str(response.question_id))
                    if question and question.topic:
                        if question.topic not in weak_areas:
                            weak_areas.append(question.topic)
            
            # Determine if passed
            passed = score >= quiz.passing_score
            
            # Update attempt with final score
            await db.execute(
                update(QuizAttempt)
                .where(QuizAttempt.id == attempt.id)
                .values(
                    score=score,
                    passed=passed,
                )
            )
            
            # Update learning state
            await db.execute(
                update(LearningState)
                .where(LearningState.user_id == UUID(user_id))
                .where(LearningState.book_id == quiz.book_id)
                .values(
                    quiz_mode="none",
                    comprehension_score=score,
                    updated_at=datetime.utcnow(),
                )
            )
            
            await db.commit()
            
            logger.info(
                "quiz_results_processed",
                user_id=user_id,
                quiz_id=quiz_id,
                score=score,
                passed=passed,
                weak_areas=weak_areas,
            )
            
            return {
                "success": True,
                "quiz_id": quiz_id,
                "score": score,
                "passed": passed,
                "correct_count": correct_count,
                "total_count": total_count,
                "weak_areas": weak_areas,
                "chapter_id": str(quiz.chapter_id),
            }
            
        except Exception as e:
            await db.rollback()
            logger.exception("process_quiz_results_failed", error=str(e))
            return {"success": False, "error": str(e)}


@activity.defn
async def create_quiz_attempt(
    user_id: str,
    quiz_id: str,
) -> dict:
    """
    Create a new quiz attempt.
    
    Args:
        user_id: The user's ID
        quiz_id: The quiz ID
        
    Returns:
        Dict with attempt info
    """
    activity.logger.info(f"Creating quiz attempt for user {user_id}, quiz {quiz_id}")
    
    async with await get_db_session() as db:
        try:
            # Get quiz
            quiz_result = await db.execute(
                select(Quiz).where(Quiz.id == UUID(quiz_id))
            )
            quiz = quiz_result.scalar_one_or_none()
            
            if not quiz:
                return {"success": False, "error": "Quiz not found"}
            
            # Get learning state
            state_result = await db.execute(
                select(LearningState)
                .where(LearningState.user_id == UUID(user_id))
                .where(LearningState.book_id == quiz.book_id)
            )
            learning_state = state_result.scalar_one_or_none()
            
            # Create attempt
            attempt = QuizAttempt(
                id=uuid4(),
                user_id=UUID(user_id),
                quiz_id=UUID(quiz_id),
                learning_state_id=learning_state.id if learning_state else None,
                started_at=datetime.utcnow(),
            )
            db.add(attempt)
            await db.commit()
            
            logger.info(
                "quiz_attempt_created",
                attempt_id=str(attempt.id),
                quiz_id=quiz_id,
                user_id=user_id,
            )
            
            return {
                "success": True,
                "attempt_id": str(attempt.id),
                "quiz_id": quiz_id,
                "total_questions": quiz.total_questions,
                "time_limit_minutes": quiz.time_limit_minutes,
            }
            
        except Exception as e:
            await db.rollback()
            logger.exception("create_attempt_failed", error=str(e))
            return {"success": False, "error": str(e)}


@activity.defn
async def get_quiz_questions(
    quiz_id: str,
) -> dict:
    """
    Get all questions for a quiz.
    
    Args:
        quiz_id: The quiz ID
        
    Returns:
        Dict with questions
    """
    async with await get_db_session() as db:
        try:
            result = await db.execute(
                select(QuizQuestion)
                .where(QuizQuestion.quiz_id == UUID(quiz_id))
                .order_by(QuizQuestion.created_at)
            )
            questions = result.scalars().all()
            
            return {
                "success": True,
                "questions": [
                    {
                        "id": str(q.id),
                        "question_text": q.question_text,
                        "question_type": q.question_type,
                        "options": q.options,
                        "difficulty": q.difficulty,
                        "topic": q.topic,
                    }
                    for q in questions
                ],
                "total": len(questions),
            }
            
        except Exception as e:
            logger.exception("get_quiz_questions_failed", error=str(e))
            return {"success": False, "error": str(e)}
