'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import ReactMarkdown from 'react-markdown';
import {
  Brain,
  ArrowLeft,
  Send,
  BookOpen,
  Settings,
  BarChart3,
  User,
  Loader2,
  CheckCircle,
  AlertCircle,
  BookmarkPlus,
  StickyNote,
} from 'lucide-react';

import api from '@/lib/api';
import SelectionToNotes from '@/components/SelectionToNotes';
import { notesStore, NotePage } from '@/lib/notes-store';

// Types matching backend models
interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  agent_name?: string;
  is_quiz_question?: boolean;
  quiz_answer_correct?: boolean;
  created_at: string;
}

interface LearningState {
  current_chapter: number;
  completed_chapters: number[];
  motivation_score: number;
  attention_score: number;
  comprehension_score: number;
  total_study_time_minutes: number;
}

interface BookInfo {
  id: string;
  title: string;
  author: string | null;
  chapters: {
    id: string;
    chapter_number: number;
    title: string | null;
  }[];
}

interface ChatSession {
  id: string;
  messages: Message[];
}

export default function LearnPage() {
  const params = useParams();
  const router = useRouter();
  const bookId = params.id as string;

  // State
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isFetching, setIsFetching] = useState(true);
  const [showSidebar, setShowSidebar] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Learning state from backend
  const [learningState, setLearningState] = useState<LearningState | null>(null);
  const [bookInfo, setBookInfo] = useState<BookInfo | null>(null);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [mode, setMode] = useState<'teaching' | 'quiz' | 'attention_check' | 'error'>('teaching');

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const messagesContainerRef = useRef<HTMLDivElement>(null);

  // Notes toast
  const [noteToast, setNoteToast] = useState<{ show: boolean; message: string }>({ show: false, message: '' });

  // Handle note saved
  const handleNoteSaved = (note: NotePage) => {
    setNoteToast({ show: true, message: `Note saved: "${note.title}"` });
    setTimeout(() => setNoteToast({ show: false, message: '' }), 3000);
  };

  // Get auth token from localStorage
  const getToken = useCallback(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('professor_access_token') || '';
    }
    return '';
  }, []);

  // Scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Load initial data from backend
  // Uses initSession API to get professor's greeting (generated by GreetingAgent, NOT hardcoded)
  useEffect(() => {
    const loadData = async () => {
      const token = getToken();
      if (!token) {
        router.push('/login');
        return;
      }

      try {
        setIsFetching(true);
        setError(null);

        // Use initSession to get the existing session with professor's greeting
        // This ensures we always load the agent-generated greeting, not hardcoded text
        const [book, state, sessionData] = await Promise.all([
          api.books.get(token, bookId),
          api.learning.getState(token, bookId),
          api.chat.initSession(token, bookId).catch((err) => {
            // Handle case where session doesn't exist yet
            console.warn('No session found, will create on first message:', err);
            return null;
          }),
        ]);

        setBookInfo(book);
        setLearningState(state);

        if (sessionData && sessionData.messages.length > 0) {
          // Session exists with professor's greeting - load it
          setSessionId(sessionData.session_id);
          setMode(sessionData.phase as any);
          
          // Load messages from the session (includes professor's greeting)
          setMessages(sessionData.messages.map((m: any) => ({
            id: m.id,
            role: m.role,
            content: m.content,
            agent_name: m.agent_name,
            is_quiz_question: m.is_quiz_question,
            quiz_answer_correct: m.quiz_answer_correct,
            created_at: m.created_at,
          })));
        } else {
          // No session yet - this shouldn't happen normally since greeting is auto-generated
          // But we handle it by triggering greeting regeneration
          try {
            const greetingResponse = await api.chat.regenerateGreeting(token, bookId);
            setSessionId(greetingResponse.session_id);
            setMessages([{
              id: `greeting-${Date.now()}`,
              role: 'assistant',
              content: greetingResponse.message,
              agent_name: 'GreetingAgent',
              created_at: new Date().toISOString(),
            }]);
          } catch (greetingErr: any) {
            console.error('Failed to generate greeting:', greetingErr);
            // Fallback: Let user send first message to trigger greeting
            setMessages([]);
          }
        }
      } catch (err: any) {
        console.error('Failed to load learning data:', err);
        setError(err.message || 'Failed to load learning data');
      } finally {
        setIsFetching(false);
      }
    };

    loadData();
  }, [bookId, getToken, router]);

  // Send message to backend (purely API-driven, no string matching!)
  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const token = getToken();
    if (!token) {
      router.push('/login');
      return;
    }

    const userMessage: Message = {
      id: `temp-${Date.now()}`,
      role: 'user',
      content: input,
      created_at: new Date().toISOString(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);
    setError(null);

    try {
      // Call backend API - this routes through LangGraph agents
      const response = await api.chat.send(token, {
        message: input,
        session_id: sessionId || undefined,
        book_id: bookId,
      });

      // Update session ID if new session was created
      if (!sessionId) {
        setSessionId(response.session_id);
      }

      // Update mode from response
      setMode(response.mode as any);

      // Add assistant message from backend
      const assistantMessage: Message = {
        id: `resp-${Date.now()}`,
        role: 'assistant',
        content: response.message,
        is_quiz_question: !!response.quiz_question,
        created_at: new Date().toISOString(),
      };

      setMessages((prev) => [...prev, assistantMessage]);

      // Refresh learning state to get updated progress
      const updatedState = await api.learning.getState(token, bookId);
      setLearningState(updatedState);

    } catch (err: any) {
      console.error('Chat error:', err);
      setError(err.message || 'Failed to send message');
      
      // Add error message
      setMessages((prev) => [...prev, {
        id: `error-${Date.now()}`,
        role: 'assistant',
        content: `I'm having trouble processing your request. ${err.message || 'Please try again.'}`,
        created_at: new Date().toISOString(),
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  // Calculate progress percentage
  const progress = learningState && bookInfo?.chapters.length
    ? Math.round((learningState.completed_chapters.length / bookInfo.chapters.length) * 100)
    : 0;

  // Loading state
  if (isFetching) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin text-blue-600 mx-auto mb-4" />
          <p className="text-gray-600">Loading your learning session...</p>
        </div>
      </div>
    );
  }

  // Error state
  if (error && !bookInfo) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <AlertCircle className="h-8 w-8 text-red-600 mx-auto mb-4" />
          <p className="text-gray-900 font-medium mb-2">Failed to load</p>
          <p className="text-gray-600 mb-4">{error}</p>
          <Link 
            href="/dashboard"
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Back to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Sidebar */}
      {showSidebar && (
        <aside className="w-80 bg-white border-r flex flex-col">
          {/* Book Info */}
          <div className="p-4 border-b">
            <Link
              href="/dashboard"
              className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 mb-4"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Dashboard
            </Link>
            <h2 className="font-semibold text-gray-900 mb-1">
              {bookInfo?.title || 'Loading...'}
            </h2>
            {bookInfo?.author && (
              <p className="text-sm text-gray-600">by {bookInfo.author}</p>
            )}
          </div>

          {/* Progress */}
          <div className="p-4 border-b">
            <div className="flex items-center justify-between text-sm mb-2">
              <span className="text-gray-600">Overall Progress</span>
              <span className="font-medium">{progress}%</span>
            </div>
            <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
              <div
                className="h-full bg-blue-600 rounded-full transition-all duration-500"
                style={{ width: `${progress}%` }}
              />
            </div>
            
            {/* Learning Metrics */}
            {learningState && (
              <div className="mt-4 grid grid-cols-3 gap-2 text-center">
                <div className="p-2 bg-green-50 rounded-lg">
                  <div className="text-lg font-semibold text-green-700">
                    {Math.round(learningState.comprehension_score * 100)}%
                  </div>
                  <div className="text-xs text-green-600">Comprehension</div>
                </div>
                <div className="p-2 bg-blue-50 rounded-lg">
                  <div className="text-lg font-semibold text-blue-700">
                    {Math.round(learningState.attention_score * 100)}%
                  </div>
                  <div className="text-xs text-blue-600">Attention</div>
                </div>
                <div className="p-2 bg-purple-50 rounded-lg">
                  <div className="text-lg font-semibold text-purple-700">
                    {learningState.total_study_time_minutes}m
                  </div>
                  <div className="text-xs text-purple-600">Study Time</div>
                </div>
              </div>
            )}
          </div>

          {/* Chapters */}
          <div className="flex-1 overflow-y-auto">
            <div className="p-4">
              <h3 className="text-sm font-medium text-gray-500 mb-3">Chapters</h3>
              <div className="space-y-1">
                {bookInfo?.chapters.map((chapter) => (
                  <ChapterItem
                    key={chapter.id}
                    number={chapter.chapter_number}
                    title={chapter.title || `Chapter ${chapter.chapter_number}`}
                    isCurrent={chapter.chapter_number === learningState?.current_chapter}
                    isCompleted={learningState?.completed_chapters.includes(chapter.chapter_number) || false}
                    isLocked={chapter.chapter_number > (learningState?.current_chapter || 1)}
                  />
                ))}
              </div>
            </div>
          </div>

          {/* Settings */}
          <div className="p-4 border-t">
            <Link 
              href="/settings"
              className="w-full flex items-center gap-2 px-3 py-2 text-gray-600 hover:bg-gray-100 rounded-lg transition"
            >
              <Settings className="h-4 w-4" />
              <span className="text-sm">Learning Settings</span>
            </Link>
          </div>
        </aside>
      )}

      {/* Main Chat Area */}
      <main className="flex-1 flex flex-col">
        {/* Header */}
        <header className="bg-white border-b px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button
              onClick={() => setShowSidebar(!showSidebar)}
              className="p-2 hover:bg-gray-100 rounded-lg transition"
            >
              <BookOpen className="h-5 w-5 text-gray-600" />
            </button>
            <div>
              <h1 className="font-semibold text-gray-900">
                Chapter {learningState?.current_chapter || 1}
                {bookInfo?.chapters.find(c => c.chapter_number === learningState?.current_chapter)?.title && 
                  `: ${bookInfo.chapters.find(c => c.chapter_number === learningState?.current_chapter)?.title}`
                }
              </h1>
              <p className="text-sm text-gray-600">
                {mode === 'quiz' && '📝 Quiz Mode • '}
                {mode === 'attention_check' && '🧠 Quick Check • '}
                Strict mode enabled
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button className="p-2 hover:bg-gray-100 rounded-lg transition" title="Progress">
              <BarChart3 className="h-5 w-5 text-gray-600" />
            </button>
          </div>
        </header>

        {/* Error Banner */}
        {error && (
          <div className="bg-red-50 border-b border-red-200 px-6 py-3 flex items-center gap-2 text-red-700">
            <AlertCircle className="h-4 w-4" />
            <span className="text-sm">{error}</span>
            <button 
              onClick={() => setError(null)}
              className="ml-auto text-red-500 hover:text-red-700"
            >
              ✕
            </button>
          </div>
        )}

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-6" ref={messagesContainerRef}>
          <div className="max-w-3xl mx-auto space-y-6">
            {messages.map((message) => (
              <MessageBubble 
                key={message.id} 
                message={message} 
                bookInfo={bookInfo}
                learningState={learningState}
                onSaveToNotes={handleNoteSaved}
              />
            ))}
            {isLoading && <TypingIndicator />}
            <div ref={messagesEndRef} />
          </div>
          
          {/* Selection to Notes - appears when text is selected */}
          <SelectionToNotes
            containerRef={messagesContainerRef}
            context={{
              bookId: bookInfo?.id,
              bookTitle: bookInfo?.title,
              chapterNumber: learningState?.current_chapter,
              chapterTitle: bookInfo?.chapters.find(c => c.chapter_number === learningState?.current_chapter)?.title || undefined,
            }}
            onNoteSaved={handleNoteSaved}
          />
        </div>
        
        {/* Note saved toast */}
        {noteToast.show && (
          <div className="fixed bottom-24 right-6 bg-green-600 text-white px-4 py-3 rounded-lg shadow-lg flex items-center gap-2 animate-fadeIn z-50">
            <StickyNote className="h-4 w-4" />
            <span className="text-sm">{noteToast.message}</span>
          </div>
        )}

        {/* Input Area */}
        <div className="bg-white border-t p-4">
          <div className="max-w-3xl mx-auto">
            <div className="flex items-end gap-4">
              <div className="flex-1 bg-gray-50 rounded-xl border focus-within:border-blue-300 focus-within:ring-2 focus-within:ring-blue-100">
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      handleSend();
                    }
                  }}
                  placeholder={
                    mode === 'quiz' 
                      ? "Type your answer..." 
                      : "Ask a question about the chapter..."
                  }
                  className="w-full px-4 py-3 bg-transparent resize-none outline-none min-h-[48px] max-h-[200px]"
                  rows={1}
                  disabled={isLoading}
                />
              </div>
              <button
                onClick={handleSend}
                disabled={!input.trim() || isLoading}
                className="p-3 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isLoading ? (
                  <Loader2 className="h-5 w-5 animate-spin" />
                ) : (
                  <Send className="h-5 w-5" />
                )}
              </button>
            </div>
            <p className="text-xs text-gray-500 mt-2 text-center">
              Professor is focused on Chapter {learningState?.current_chapter || 1}. 
              Complete the quiz to unlock the next chapter.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}

// Chapter Item Component
function ChapterItem({
  number,
  title,
  isCurrent,
  isCompleted,
  isLocked,
}: {
  number: number;
  title: string;
  isCurrent: boolean;
  isCompleted: boolean;
  isLocked: boolean;
}) {
  return (
    <button
      disabled={isLocked}
      className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-left transition ${
        isCurrent
          ? 'bg-blue-50 text-blue-700'
          : isCompleted
          ? 'hover:bg-gray-50 text-gray-900'
          : 'text-gray-400 cursor-not-allowed'
      }`}
    >
      <div
        className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-medium ${
          isCurrent
            ? 'bg-blue-600 text-white'
            : isCompleted
            ? 'bg-green-500 text-white'
            : 'bg-gray-200 text-gray-500'
        }`}
      >
        {isCompleted ? <CheckCircle className="h-4 w-4" /> : number}
      </div>
      <span className="text-sm truncate flex-1">{title}</span>
      {isLocked && <span className="text-xs">🔒</span>}
    </button>
  );
}

// Message Bubble Component  
function MessageBubble({ 
  message,
  bookInfo,
  learningState,
  onSaveToNotes,
}: { 
  message: Message;
  bookInfo: BookInfo | null;
  learningState: LearningState | null;
  onSaveToNotes: (note: NotePage) => void;
}) {
  const isUser = message.role === 'user';
  const [showSaveButton, setShowSaveButton] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const handleSaveFullMessage = async () => {
    if (isSaving) return;
    setIsSaving(true);

    try {
      const note = await notesStore.createFromSelection({
        selectedText: message.content,
        messageContent: message.content,
        messageId: message.id,
        agentName: message.agent_name,
        bookId: bookInfo?.id,
        bookTitle: bookInfo?.title,
        chapterNumber: learningState?.current_chapter,
        chapterTitle: bookInfo?.chapters.find(c => c.chapter_number === learningState?.current_chapter)?.title || undefined,
      });
      onSaveToNotes(note);
    } catch (error) {
      console.error('Failed to save note:', error);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div
      className={`flex gap-3 animate-fadeIn group ${
        isUser ? 'flex-row-reverse' : ''
      }`}
      onMouseEnter={() => !isUser && setShowSaveButton(true)}
      onMouseLeave={() => setShowSaveButton(false)}
    >
      <div
        className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${
          isUser ? 'bg-blue-600' : 'bg-gradient-to-br from-blue-500 to-purple-600'
        }`}
      >
        {isUser ? (
          <User className="h-4 w-4 text-white" />
        ) : (
          <Brain className="h-4 w-4 text-white" />
        )}
      </div>
      <div
        className={`max-w-[80%] rounded-2xl px-4 py-3 relative ${
          isUser
            ? 'bg-blue-600 text-white'
            : message.is_quiz_question
            ? 'bg-yellow-50 border-2 border-yellow-200'
            : 'bg-white border shadow-sm'
        }`}
        data-message-id={message.id}
        data-agent-name={message.agent_name || ''}
      >
        <div className={`prose prose-sm max-w-none ${isUser ? 'prose-invert' : ''}`}>
          <ReactMarkdown
            components={{
              p: ({children}) => <p className="mb-2 last:mb-0">{children}</p>,
              strong: ({children}) => <strong className="font-semibold">{children}</strong>,
              ul: ({children}) => <ul className="list-disc pl-4 my-2">{children}</ul>,
              ol: ({children}) => <ol className="list-decimal pl-4 my-2">{children}</ol>,
              li: ({children}) => <li className="mb-1">{children}</li>,
              h1: ({children}) => <h1 className="text-lg font-bold mt-3 mb-2">{children}</h1>,
              h2: ({children}) => <h2 className="text-base font-bold mt-2 mb-1">{children}</h2>,
              h3: ({children}) => <h3 className="text-sm font-semibold mt-2 mb-1">{children}</h3>,
              code: ({children}) => <code className="bg-gray-100 px-1 py-0.5 rounded text-sm">{children}</code>,
            }}
          >
            {message.content}
          </ReactMarkdown>
        </div>
        
        {/* Footer with agent name and save button */}
        {!isUser && (
          <div className="mt-2 flex items-center justify-between">
            {message.agent_name && (
              <span className="text-xs text-gray-400">
                via {message.agent_name}
              </span>
            )}
            
            {/* Save to Notes button - visible on hover */}
            {showSaveButton && (
              <button
                onClick={handleSaveFullMessage}
                disabled={isSaving}
                className="flex items-center gap-1 text-xs text-gray-400 hover:text-blue-600 transition-colors ml-auto"
                title="Save entire message to notes"
              >
                {isSaving ? (
                  <Loader2 className="h-3 w-3 animate-spin" />
                ) : (
                  <BookmarkPlus className="h-3 w-3" />
                )}
                <span>Save to Notes</span>
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// Typing Indicator Component
function TypingIndicator() {
  return (
    <div className="flex gap-3 animate-fadeIn">
      <div className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
        <Brain className="h-4 w-4 text-white" />
      </div>
      <div className="bg-white border shadow-sm rounded-2xl px-4 py-3 flex items-center gap-1">
        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
      </div>
    </div>
  );
}
