"""Add learning configuration tables.

Revision ID: 0003_learning_config
Revises: 0002
Create Date: 2026-01-14

Per Goals.md, these tables store:
- User learning preferences from upload (Step 1)
- Learning plans generated by Planner Agent (Step 4)
- Conversation state tracking
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY


# revision identifiers, used by Alembic.
revision = '0003_learning_config'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # Add new columns to books table
    op.add_column('books', sa.Column('professor_greeted', sa.Boolean(), nullable=True, default=False))
    op.add_column('books', sa.Column('professor_greeting_at', sa.DateTime(), nullable=True))
    
    # Create learning_configs table
    op.create_table(
        'learning_configs',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('user_id', UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('book_id', UUID(as_uuid=True), sa.ForeignKey('books.id', ondelete='CASCADE'), nullable=False, unique=True, index=True),
        
        # Learning Level
        sa.Column('learning_level', sa.String(50), nullable=False, default='intermediate'),
        
        # Chapter Selection
        sa.Column('study_all_chapters', sa.Boolean(), default=True),
        sa.Column('selected_chapters', ARRAY(sa.Integer()), nullable=True),
        
        # Timeline
        sa.Column('deadline', sa.Date(), nullable=True),
        sa.Column('preferred_study_days', ARRAY(sa.String(10)), nullable=True),
        sa.Column('daily_study_minutes', sa.Integer(), default=60),
        
        # Quiz Preferences
        sa.Column('quiz_frequency', sa.String(30), nullable=False, default='after_each_chapter'),
        sa.Column('quiz_after_n_chapters', sa.Integer(), nullable=True),
        sa.Column('questions_per_quiz', sa.Integer(), default=5),
        sa.Column('quiz_difficulty', sa.String(20), default='match_level'),
        
        # Reminder Settings
        sa.Column('enable_reminders', sa.Boolean(), default=True),
        sa.Column('reminder_channel', sa.String(20), default='push'),
        sa.Column('inactivity_threshold_hours', sa.Integer(), default=24),
        
        # Plan Status
        sa.Column('plan_generated', sa.Boolean(), default=False),
        sa.Column('plan_accepted', sa.Boolean(), default=False),
        sa.Column('plan_accepted_at', sa.DateTime(), nullable=True),
        
        # Timestamps
        sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), default=sa.func.now(), onupdate=sa.func.now()),
    )
    
    # Create learning_plans table
    op.create_table(
        'learning_plans',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('config_id', UUID(as_uuid=True), sa.ForeignKey('learning_configs.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('user_id', UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('book_id', UUID(as_uuid=True), sa.ForeignKey('books.id', ondelete='CASCADE'), nullable=False, index=True),
        
        # Plan Data
        sa.Column('plan_data', JSONB, nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('version', sa.Integer(), default=1),
        sa.Column('status', sa.String(20), default='draft'),
        sa.Column('user_feedback', sa.Text(), nullable=True),
        
        # Timestamps
        sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
    )
    
    # Create conversation_states table
    op.create_table(
        'conversation_states',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('user_id', UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('book_id', UUID(as_uuid=True), sa.ForeignKey('books.id', ondelete='CASCADE'), nullable=False, index=True),
        
        # Current Phase
        sa.Column('phase', sa.String(30), nullable=False, default='greeting'),
        
        # Chapter Context
        sa.Column('current_chapter', sa.Integer(), default=1),
        sa.Column('current_topic_index', sa.Integer(), default=0),
        sa.Column('chapters_taught', ARRAY(sa.Integer()), default=[]),
        sa.Column('chapters_quizzed', ARRAY(sa.Integer()), default=[]),
        sa.Column('doubts_cleared', sa.Boolean(), default=False),
        
        # Professor Context
        sa.Column('last_professor_action', sa.String(100), nullable=True),
        sa.Column('workflow_id', sa.String(200), nullable=True),
        
        # Timestamps
        sa.Column('last_interaction_at', sa.DateTime(), default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
    )
    
    # Create unique constraint on conversation_states (user_id, book_id)
    op.create_unique_constraint(
        'uq_conversation_state_user_book',
        'conversation_states',
        ['user_id', 'book_id']
    )


def downgrade():
    op.drop_table('conversation_states')
    op.drop_table('learning_plans')
    op.drop_table('learning_configs')
    op.drop_column('books', 'professor_greeting_at')
    op.drop_column('books', 'professor_greeted')
