#!/bin/bash

# Professor Frontend Environment Setup Script
# Run this script to create the .env.local file

echo "Setting up Professor frontend environment..."

# Check if .env.local already exists
if [ -f .env.local ]; then
    echo ".env.local already exists. Backing up to .env.local.bak"
    cp .env.local .env.local.bak
fi

# Create .env.local from template
cat > .env.local << 'EOF'
# Professor Frontend Environment Variables
# Generated by setup-env.sh

# Backend API URL
NEXT_PUBLIC_API_URL=http://localhost:8000

# Google OAuth Client ID (same as backend)
NEXT_PUBLIC_GOOGLE_CLIENT_ID=your-google-client-id.apps.googleusercontent.com

# App Settings
NEXT_PUBLIC_APP_NAME=Professor
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

echo ""
echo "✅ Created .env.local"
echo ""
echo "⚠️  IMPORTANT: Please edit .env.local and set your Google Client ID:"
echo "   NEXT_PUBLIC_GOOGLE_CLIENT_ID=your-actual-client-id"
echo ""
echo "Then run: npm install && npm run dev"
